### ISSUE TITLE
Earliest Version of Forge / Minecraft?

### ISSUE THREAD

**Issue by CubityFirst** [MoSadie/EffectMC#15]
Out of curiosity, what's the earliest version of Forge / Minecraft this will support? Would love to use it for Skyblock (1.8.9) but not sure if it'd work.

**Comment by MoSadie** [comment]
Right now the earliest version is for 1.12, but I can look into seeing if 1.8.9 is possible.

**Comment by MoSadie** [comment]
Current status on a 1.8.9 backport: Mostly complete!

Todo:
- [X] Get 1.8.9 mdk setup
- [X] Import core
- [X] Replicate as many effects as possible (current missing effects: Narrator. Toast and Action Bar having to think outside the box)
- [ ] Fix OpenBook (might just give up on this one, trying to parse JSON into NBT is painful)
- [ ] Check if OpenScreen is still crashing.
- [ ] Release it

**Comment by MoSadie** [comment]
Should be releasing now on the various modding platforms!

- Modrinth: https://modrinth.com/mod/effectmc/version/Forge-1.8.9-v2.2.0
- GitHub: https://github.com/MoSadie/EffectMC/releases/tag/v2.2.0
- CurseForge: https://legacy.curseforge.com/minecraft/mc-mods/effectmc/files/4625821 (soon, waiting for review)
