### ISSUE TITLE
please Update to 1.19

### ISSUE THREAD

**Issue by ikuria** [MoSadie/EffectMC#19]
1.18 isnt working with 1.19 Minecraft - please Update <3

**Comment by MoSadie** [comment]
Working on this right now! Should be released in a day or two.

**Comment by MoSadie** [comment]
Done! Should be now available on [the GitHub release](https://github.com/MoSadie/EffectMC/releases/tag/v2.1.0), [CurseForge](https://www.curseforge.com/minecraft/mc-mods/effectmc/files), and [Modrinth](https://modrinth.com/mod/effectmc/versions)!
