### ISSUE TITLE
Update to 1.19.3

### ISSUE THREAD

**Issue by MoSadie** [MoSadie/EffectMC#25]
1.19.3 has a lot of internal changes that affect mods. Shouldn't break too much but we'll see.

EDIT: Thanks to @tayadev fabric support has just been merged, now all's that's left is forge

**Comment by tayadev** [comment]
just noticed that CI doesn't include a 1.19.3 build yet, we'd have to add it to the version matrix

**Comment by MoSadie** [comment]
True, I'll add it when I push up Forge 1.19.3, shouldn't be more than a few minutes.

**Comment by MoSadie** [comment]
CI worked, all good to go for this part of the update.
