### ISSUE TITLE
Feature request: use default address if none specified

### ISSUE THREAD

**Issue by purple512** [MoSadie/EffectMC#28]
Hi,

I'm using the Stream Deck app and the default Minecraft address (`http://localhost:3000`) but every time I add a new action I have to manually fill in this field, even though it shows the default in grayed out form. If I leave the field blank I get an exclamation point warning symbol when I press the button and it does not work.

Would it be possible to simply use `http://localhost:3000` if the field is blank, instead of error? It would really simplify my day.

Thank you for an excellent piece of software.

**Comment by MoSadie** [comment]
I have an idea for something in the middle.
What I will do have it pre-fill the default address, so it is there by default.

The grayed out text is known as a placeholder, like how some websites say "Password" in the password field until you enter a password. Without any text in the address field it doesn't know where to send the effect trigger, so the exclamation mark indicates something went wrong.

I still want a blank address field to cause an error, but pre-filling it should help a lot.

Glad to hear you like this mod!

**Comment by purple512** [comment]
That sounds great, thank you!

**Comment by MoSadie** [comment]
Added in [v2.3.0](https://github.com/MoSadie/EffectMC/releases/tag/v2.3.0).

Sorry for the delay!
