### ISSUE TITLE
Send Chat: Sends directly to server, instead MC instance?

### ISSUE THREAD

**Issue by CobbleShop** [MoSadie/EffectMC#43]
Hey. Once of my first github issues, so please bare with me.

I found that when trying to trigger "/ct load" it sends this chat message to the server, instead of ChatTriggers Mod. 

Is there a way to inject "Send Chat" to the client, maybe?

How i found out:
Hypixel responded with "You must be admin or higher to execute this command", instead of actually reloading my ChatTrigger Modules

**Comment by MoSadie** [comment]
Hmm that's odd...

What version of Minecraft, EffectMC, and ChatTriggers are you using? That will help me try to reproduce the issue.

**Comment by CobbleShop** [comment]
> Hmm that's odd...
> 
> What version of Minecraft, EffectMC, and ChatTriggers are you using? That will help me try to reproduce the issue.

Minecraft 1.8.9 Forge
effectmc-forge-1.8.9-2.2.0.jar
ctjs-2.2.0-1.8.9

Other mods present:
NotEnoughUpdates-2.1.1-Alpha-27.jar
Patcher-1.8.7 (1.8.9).jar
preview_OptiFine_1.8.9_HD_U_M6_pre2.jar
SkyblockAddons-1.7.37380-for-MC-1.8.9.jar
Skytils-1.8.3.jar

**Comment by MoSadie** [comment]
I have a theory for why it may not work, it's likely related to how EffectMC is sending chat messages. (It may be skipping client commands) 

I can take a closer look in ~8 hours when I get off work.

**Comment by MoSadie** [comment]
Got it figured out, looks like my mod was skipping the client commands, pushing a new update out right now to fix that. Should be live on the releases page and Modrinth now, but CF takes a few minutes to approve it.

**Comment by CobbleShop** [comment]
Working great. Thank you so much <3
