### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by jakestrash** [MoSadie/EffectMC#47]
The mod needs support for 1.21

**Comment by MoSadie** [comment]
Can confirm I'm working on it, got 99% of it updated so far, but running into one bug that needs to be fixed before I can release the update. I'll update here when 1.21 support is ready. The goal is to have it out this weekend.

**Comment by MoSadie** [comment]
Sorry for the delay, got busy. But good news! Got the update pushed to all the major platforms. Should be live on GitHub Releases and Modrinth now, with CurseForge hopefully approving it soon.
