### ISSUE TITLE
Unable to trust StreamDeck

### ISSUE THREAD

**Issue by IxIHEADCASEIxI** [MoSadie/EffectMC#58]
Using Prism Launcher, 3 different instances tested, using Stream Deck XL.

- > NeoForge 20.4.238 Minecraft 1.20.4
- > NeoForge 21.1.90 Minecraft 1.21.1
- > Forge 47.3.11 Minecraft 1.20.1

I can trust my device and send events/commands using  NeoForge 21.1.90  Minecraft 1.21.1 using my stream deck.
Once I trusted the device, I can no longer trust the device in another instance. I can see in the logs/console, where Effectmc is waiting and receiving a button press. Nothing shows up in-game to accept or deny the device.
I have tried:

- Manually copying over the `trust.json` file to the other 2 instances.
- Instances with only EffectMC installed. (No shaders, No extra anything added, Strictly Forge or NeoForge with the corresponding EffectMC ) 
- Trusting and Sending commands from "localhost:3000" in each instance. ( This method works, for just the browser. Trying to switch to Stream Deck does not)

--------------------------------------------------------------------------------------------------------------------------------------------

- >[21:04:55] [Render thread/INFO] [co.mo.ef.EffectMC/]: Showing chat message: [EffectMC] Now prompting to trust the next request sent.

- >[21:04:55] [Render thread/INFO] [minecraft/ChatComponent]: [System] [CHAT] [EffectMC] Now prompting to trust the next request sent.

- >[21:04:57] [HTTP-Dispatcher/INFO] [co.mo.ef.EffectMC/]: Showing homepage!

- >[21:05:02] [HTTP-Dispatcher/INFO] [co.mo.ef.EffectMC/]: Showing homepage!

- >[21:05:03] [HTTP-Dispatcher/INFO] [co.mo.ef.EffectMC/]: Showing homepage!

**Comment by MoSadie** [comment]
I'm out of town right now, so I may not be able to respond quickly, but just checking, which version of the mod is being used for each version? The file name should have something like v3.0.0 with the Minecraft version.

Or if you're not sure, can you send me the instances via Discord?

**Comment by MoSadie** [comment]
If I had to guess, based on the game versions you mentioned, the two instances that aren't working may not have v3.0.0 of EffectMC

When I did the v3.0.0 update I rewrote the Steam Deck plugin, so it's incompatible with the older versions. I'll work on getting an updated Forge 1.20.1 and NeoForge 1.20.4 version out in the next day or so.

**Comment by IxIHEADCASEIxI** [comment]
No rush at all, Enjoy your time.
This is the version/setup that I am able to get EffectMC working on. ``NeoForge 21.1.90 Minecraft 1.21.1 EffectMc 3.1.0``
Not saying other versions do not work, 

        NeoForge 20.4.238 Minecraft 1.20.4 EffectMc 2.3.0

        NeoForge 21.1.90 Minecraft 1.21.1 EffectMc 3.1.0

        Forge 47.3.11 Minecraft 1.20.1 EffectMc 2.2.0

**Comment by MoSadie** [comment]
Sorry for the delay, but got some updated versions for you for the versions you gave, can you try those out and see if that fixed it?

Forge 1.20.1: https://modrinth.com/mod/effectmc/version/Forge-1.20.1-v3.1.0
NeoForge 1.20.4: https://modrinth.com/mod/effectmc/version/NeoForge-1.20.4-v3.1.0

Thanks!

**Comment by IxIHEADCASEIxI** [comment]
Checked both versions, I'm not having any issues. I'm able to trust device.
Thanks for the update!
Happy holidays!

**Comment by MoSadie** [comment]
Glad to hear, happy holidays!
